version: '3.9'
services:
  etl:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./data:/opt/data
    command: ["./wait-for-postgres.sh", "postgres", "python", "main.py", "--source", "/opt/data/activity.csv", "--database", "warehouse", "--table", "user_activity"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
